-- Migration: assistant_orchestration_tables
-- Creates the 3 core tables for Athena's Intelligent Orchestration layer

-- ═══════════════════════════════════════════════════
-- 1. assistant_suggestions
-- Proactive suggestions generated by the Athena scan engine
-- ═══════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.assistant_suggestions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  office_id     UUID NOT NULL REFERENCES public.offices(id) ON DELETE CASCADE,
  user_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  category      TEXT NOT NULL CHECK (category IN ('agenda', 'legal', 'medical', 'document', 'alert', 'followup')),
  priority      TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low')),
  title         TEXT NOT NULL,
  description   TEXT NOT NULL,
  action_type   TEXT,
  action_payload JSONB NOT NULL DEFAULT '{}',
  entity_type   TEXT,
  entity_id     UUID,
  is_dismissed  BOOLEAN NOT NULL DEFAULT false,
  is_executed   BOOLEAN NOT NULL DEFAULT false,
  executed_at   TIMESTAMPTZ,
  expires_at    TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '7 days'),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_assistant_suggestions_office_user
  ON public.assistant_suggestions (office_id, user_id);
CREATE INDEX IF NOT EXISTS idx_assistant_suggestions_expires
  ON public.assistant_suggestions (expires_at);
CREATE INDEX IF NOT EXISTS idx_assistant_suggestions_active
  ON public.assistant_suggestions (office_id, user_id, is_dismissed, is_executed, expires_at);

ALTER TABLE public.assistant_suggestions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own suggestions"
  ON public.assistant_suggestions
  FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ═══════════════════════════════════════════════════
-- 2. assistant_memory
-- User preference and behavioral pattern memory
-- ═══════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.assistant_memory (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  office_id  UUID NOT NULL REFERENCES public.offices(id) ON DELETE CASCADE,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  key        TEXT NOT NULL,
  value      TEXT NOT NULL,
  metadata   JSONB NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (office_id, user_id, key)
);

CREATE INDEX IF NOT EXISTS idx_assistant_memory_lookup
  ON public.assistant_memory (office_id, user_id);

ALTER TABLE public.assistant_memory ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own memory"
  ON public.assistant_memory
  FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ═══════════════════════════════════════════════════
-- 3. assistant_action_log
-- Full audit trail of all actions executed by the assistant
-- ═══════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.assistant_action_log (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  office_id       UUID REFERENCES public.offices(id) ON DELETE SET NULL,
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  action_type     TEXT NOT NULL,
  action_payload  JSONB NOT NULL DEFAULT '{}',
  suggestion_id   UUID REFERENCES public.assistant_suggestions(id) ON DELETE SET NULL,
  status          TEXT NOT NULL DEFAULT 'started' CHECK (status IN ('started', 'success', 'failed', 'cancelled')),
  result          JSONB DEFAULT '{}',
  error_message   TEXT,
  started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_assistant_action_log_office
  ON public.assistant_action_log (office_id, user_id);
CREATE INDEX IF NOT EXISTS idx_assistant_action_log_started
  ON public.assistant_action_log (started_at DESC);

ALTER TABLE public.assistant_action_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own action logs"
  ON public.assistant_action_log
  FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Users can insert their own action logs"
  ON public.assistant_action_log
  FOR INSERT
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update their own action logs"
  ON public.assistant_action_log
  FOR UPDATE
  USING (user_id = auth.uid());
