// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = typeof import.meta.env !== 'undefined' ? import.meta.env.VITE_SUPABASE_URL : process.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = typeof import.meta.env !== 'undefined' 
  ? (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY) 
  : (process.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_ANON_KEY);

// Security Guard: Prevent service_role key leakage in frontend
if (SUPABASE_PUBLISHABLE_KEY?.includes('service_role') || SUPABASE_PUBLISHABLE_KEY?.startsWith('sb_secret_')) {
  console.error('[SECURITY CRITICAL] Service role key detected in frontend bundle!');
  throw new Error('Critical Security Violation: Admin keys must never be exposed to the client.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof window !== 'undefined';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? localStorage : undefined,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
  }
});