export const Constants = {
  public: {
    Enums: {
      asaas_billing_type: ["PIX", "BOLETO", "CREDIT_CARD"],
      asaas_payment_status: [
        "PENDING",
        "RECEIVED",
        "CONFIRMED",
        "OVERDUE",
        "REFUNDED",
        "CANCELED",
        "ERROR",
      ],
      case_side: ["ATAQUE", "DEFESA"],
      client_file_kind: [
        "IDENTIDADE",
        "CPF_CNPJ",
        "COMPROVANTE_ENDERECO",
        "CONTRATO_ASSINADO",
        "OUTRO",
        "KIT_PROCURACAO",
        "KIT_DECLARACAO",
        "KIT_CONTRATO",
        "ASSINATURA",
        "COMPROVANTE_RENDA",
        "KIT_RECIBO",
      ],
      doc_kind: [
        "PROCURACAO",
        "DECLARACAO",
        "CONTRATO",
        "PECA",
        "ANEXO",
        "PROCESSO_PDF",
        "OUTRO",
      ],
      office_role: ["OWNER", "ADMIN", "MEMBER"],
      person_type: ["PF", "PJ"],
      person_type_enum: ["PF", "PJ"],
      precedent_job_type: ["CHECK_SOURCE"],
      precedent_kind: [
        "SUMULA",
        "ACORDAO",
        "JURISPRUDENCIA",
        "TEMA_REPETITIVO",
        "REPERcussAO_GERAL",
        "ORIENTACAO_JURISPRUDENCIAL",
        "TESE",
        "INFORMATIVO",
        "OUTRO",
      ],
      precedent_source_kind: ["OFICIAL", "SECUNDARIA"],
      precedent_status: [
        "ATIVA",
        "CANCELADA",
        "ALTERADA",
        "SUPERADA",
        "DESCONHECIDO",
      ],
      variable_context: ["GLOBAL", "LEGAL", "MEDICAL", "AGENDA"],
      variable_source: ["TABLE_FIELD", "COMPUTED", "STATIC", "CUSTOM"],
    },
  },
} as const;
